require 'faker'

User.destroy_all

users = [
	{twitter_username: "katyperry", youtube_username: "PewDieDie"},
	{twitter_username: "justinbieber", youtube_username: "Smosh"},
	{twitter_username: "BarackObama", youtube_username: "judsonlaipply"},
	{twitter_username: "taylorswift13", youtube_username: "Brookers"},
	{twitter_username: "ladygaga", youtube_username: "geriatric1927"},
	{twitter_username: "britneyspears", youtube_username: "lonelygirl15"},
	{twitter_username: "jtimberlake", youtube_username: "nigahiga"},
	{twitter_username: "rihanna", youtube_username: "Fred"},
	{twitter_username: "auria", youtube_username: "holasoygerman"},
	{twitter_username: "Cristano", youtube_username: "JennaMarbles"},
	{twitter_username: "JLo", youtube_username: "machinima"},
	{twitter_username: "shakira", youtube_username: "ERB"},
	{twitter_username: "KimKardashian", youtube_username: "TheFineBros"},
	{twitter_username: "Oprah", youtube_username: "RayWilliamJohnson"},
	{twitter_username: "ddlovato", youtube_username: "skydoesminecraft"},
	{twitter_username: "Pink", youtube_username: "TheEllenShow"},
	{twitter_username: "selenagomez", youtube_username: "vanossgaming"},
	{twitter_username: "Randy_Gage", youtube_username: "portadosfundos"},
	{twitter_username: "Harry_Styles", youtube_username: "elrubiusOMG"},
	{twitter_username: "ArianaGrande", youtube_username: "TheOfficialSkrillex"},
	{twitter_username: "KAKA", youtube_username: "werevertumorro"},
	{twitter_username: "onedirection", youtube_username: "collegehumor"},
	{twitter_username: "OfficialAdele", youtube_username: "lady16makeup"},
	{twitter_username: "NiallOfficial", youtube_username: "TheSyndicateProject"},
	{twitter_username: "aliciakeys", youtube_username: "CaptainSparklez"},
	{twitter_username: "BrunoMars", youtube_username: "vsauce"},
	{twitter_username: "LilTunechi", youtube_username: "RoosterTeeth"},
	{twitter_username: "venelibertario", youtube_username: "ElektraRecords"},
	{twitter_username: "Eminem", youtube_username: "Macbarbie07"},
	{twitter_username: "MileyCyrus", youtube_username: "vegetta777"},
	{twitter_username: "BillGates", youtube_username: "VitalyzdTv"},
	{twitter_username: "pitbull", youtube_username: "ksiolajidebt"},
	{twitter_username: "Real_Liam_Payne", youtube_username: "officialpsy"},
	{twitter_username: "NICKIMINAJ", youtube_username: "SpinninRec"},
	{twitter_username: "Louis_Tomlinson", youtube_username: "enchufetv"},
	{twitter_username: "Drake", youtube_username: "freddiew"},
	{twitter_username: "jimmyfallon", youtube_username: "MichellePhan"},
	{twitter_username: "AvrilLavigne", youtube_username: "BlueXephos"},
	{twitter_username: "aplusk", youtube_username: "PTXofficial"},
	{twitter_username: "KingJames", youtube_username: "TobyGames"},
	{twitter_username: "wizkhalifa", youtube_username: "PrankvsPrank"},
	{twitter_username: "davidguetta", youtube_username: "zoella280390"},
	{twitter_username: "neymarjr", youtube_username: "EpicMealTime"},
	{twitter_username: "EmWatson", youtube_username: "RiotGamesInc"},
	{twitter_username: "MariahCarey", youtube_username: "boyceavenue"},
	{twitter_username: "KevinHart4real", youtube_username: "MonsieurDream"},
	{twitter_username: "chrisbrown", youtube_username: "speedyw03"},
	{twitter_username: "Beyonce", youtube_username: "ShaneDawsonTV"},
	{twitter_username: "zaynmalik", youtube_username: "canalparafernalha"},
	{twitter_username: "xtina", youtube_username: "tseries"},
	{twitter_username: "JimCarrey", youtube_username: "Tobuscus"},
	{twitter_username: "ConanOBrien", youtube_username: "failarmy"},
	{twitter_username: "kourtneykardash", youtube_username: "programagalofrito"},
	{twitter_username: "ParisHilton", youtube_username: "WatchMojo"},
	{twitter_username: "RyanSeacrest", youtube_username: "thelonelyisland"},
	{twitter_username: "danieltosh", youtube_username: "tyleroakley"},
	{twitter_username: "iamwill", youtube_username: "NBA"},
	{twitter_username: "ashleytisdale", youtube_username: "movieclipsTRAILERS"},
	{twitter_username: "thomaspower", youtube_username: "lindseystomp"},
	{twitter_username: "SrBachchan", youtube_username: "SMTOWN"},
	{twitter_username: "ActuallyNPH", youtube_username: "thewillyrex"},
	{twitter_username: "agnezmo", youtube_username: "JuegaGerman"},
	{twitter_username: "tyrabanks", youtube_username: "AdamThomasMoran"},
	{twitter_username: "AlejandroSanz", youtube_username: "UKFDubstep"},
	{twitter_username: "SnoopDogg", youtube_username: "FPSRussia"},
	{twitter_username: "0xF2", youtube_username: "NormanFaitDesVideos"},
	{twitter_username: "khloekardashian", youtube_username: "IGNentertainment"},
	{twitter_username: "LeoDiCaprio", youtube_username: "vice"},
	{twitter_username: "ivetesangalo", youtube_username: "latenight"},
	{twitter_username: "charliesheen", youtube_username: "BFvsGF"},
	{twitter_username: "edsheeran", youtube_username: "Matroix"},
	{twitter_username: "ricky_martin", youtube_username: "SteveKardynal"},
	{twitter_username: "10Ronaldinho", youtube_username: "JimmyKimmelLive"},
	{twitter_username: "kanyewest", youtube_username: "SeaNanners"},
	{twitter_username: "SimonCowell", youtube_username: "RomanAtwood"},
	{twitter_username: "carlyraejepsen", youtube_username: "KurtHugoSchneider"},
	{twitter_username: "novaspivack", youtube_username: "rhettandlink2"},
	{twitter_username: "MohamadAlarefe", youtube_username: "theslowmoguys"},
	{twitter_username: "iamsrk", youtube_username: "BartBaKer"},
	{twitter_username: "WayneRooney", youtube_username: "ThisIsHorosho"},
	{twitter_username: "iamdiddy", youtube_username: "DisneyCollectorBR"},
	{twitter_username: "andresiniesta8", youtube_username: "getmovies"},
	{twitter_username: "aamir_khan", youtube_username: "blucollection"},
	{twitter_username: "ClaudiaLeitte", youtube_username: "DisneyCarToys"},
	{twitter_username: "Usher", youtube_username: "MashaMedvedTV"},
	{twitter_username: "ZacEfron", youtube_username: "buzzfeedyellow"},
	{twitter_username: "gqindia", youtube_username: "SurpriseToys"}
]

users.each_with_index do |user,index|
	User.create!(email: Faker::Internet.email, name: Faker::Name.name, blurb: Faker::Hacker.say_something_smart, image_url: "https://pbs.twimg.com/profile_images/3253620646/8031eb423b8d91cca462af4825cdfdb2.jpeg", password: "password",twitter_username: user[:twitter_username], youtube_username: user[:youtube_username])
	puts "#{index + 1} users loaded"
end

User.all.each_with_index do |user,index|
	puts "loading tweets for user #{index + 1}"
	user.load_tweets
	puts "loading videos for user #{index + 1}"
	user.load_videos
end
