# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b73b8b6d5a80378b56bfabd5e22f2c4d20a4e45a54145d37f5a02084c83b1671d6d55f659f2d2827d89ccdfe73eb9a8d882ec3051bfd6ef1141eb95e3954f31

test:
  secret_key_base: 907f362cd3f28b2ab2e5eb6ccbf499b382bf8036b26c9e9ee8e5638c119c278ad52ebc57ab26ca9b925cb5e0f2b6aab4d6cd01ddffb297c07f2e8dcf01624bd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
